#!/bin/bash

echo "=========================================="
echo "🔧 PERSIAPAN: Perbaikan Manual grading.service.ts"
echo "=========================================="
echo ""

echo "1️⃣ Backup file asli (untuk jaga-jaga)"
cp src/services/grading.service.ts src/services/grading.service.ts.bak-manual-fix
echo "✅ Backup berhasil: src/services/grading.service.ts.bak-manual-fix"
echo ""

echo "2️⃣ Buka file di VSCode (atau editor favorit Anda)"
echo "   Jalankan perintah ini di terminal TERPISAH jika VSCode tidak terbuka:"
echo "   code src/services/grading.service.ts"
echo ""

echo "=========================================="
echo "📋 PANDUAN PERBAIKAN MANUAL (Ikuti langkah ini di VSCode)"
echo "=========================================="
echo ""
echo "Langkah 1: Cari fungsi 'gradeSubmission' (kurang lebih line 100-130)."
echo ""
echo "Langkah 2: Temukan blok 'await prisma.submission.update({ ... })'."
echo ""
echo "Langkah 3: HAPUS SEMUA blok 'try { ... } catch (notifError: any) { ... }'"
echo "         yang ada di ANTARA properti object 'data'."
echo "         (Ada 8 blok: line ~143-166, 169-189, 192-212, 215-235, 238-258,"
echo "          261-281, 284-304, 307-327)."
echo ""
echo "Langkah 4: Pastikan object 'data' memiliki struktur yang VALID:"
echo "         data: {"
echo "           status: 'graded',"
echo "           total_points_earned: totalPoints,"
echo "           student_id: submission.student_id,"
echo "           quiz_id: submission.quiz_id,"
echo "           score_percentage: scorePercentage,"
echo "           passing_score: quiz.passing_score,"
echo "           time_spent_seconds: Math.floor(submission.time_spent_milliseconds / 1000) || 0,"
echo "           graded_at: new Date()"
echo "         },"
echo ""
echo "Langkah 5: SETELAH blok 'await prisma.submission.update({ ... })' selesai,"
echo "         TAMBAHKAN blok try-catch untuk notification yang BENAR:"
echo ""
echo "         // Send notification to student (setelah update berhasil)"
echo "         try {"
echo "           await notificationService.triggerSubmissionGraded("
echo "             submission_id,"
echo "             submission.student_id,"
echo "             scorePercentage,"
echo "             quiz.title"
echo "           );"
echo "         } catch (notifError: any) {"
echo "           logger.warn(`Notification failed: ${notifError.message}`);"
echo "         }"
echo ""
echo "Langkah 6: Simpan file (Ctrl+S)."
echo ""
echo "=========================================="
echo "📌 Setelah selesai, jalankan validasi:"
echo "   npx tsc --noEmit src/services/grading.service.ts"
echo "=========================================="

